#################   DETECTION CONFIG   ###################

det_weight: "/content/drive/MyDrive/AI Competitions/MC-OCR/checkpoints/detection-checkpoints/best_rotation/PANNet_best_map.pth"
det_config: "./tool/config/detection/configs.yaml"

#################   OCR CONFIG   ###################

ocr_weight: "/content/drive/MyDrive/AI Competitions/MC-OCR/checkpoints/ocr-checkpoints/transformerocr.pth"
ocr_config: "./tool/config/ocr/configs.yaml"

#################   RETRIEVAL CONFIG   ###################

retr_mode: "all"
correction_mode: "ed"
bert_weight: ""
dictionary_csv: "./retrieval/heuristic/custom-dictionary.csv"
retr_classes: [
  "SELLER",
  "ADDRESS",
  "TIMESTAMP",
  "TOTAL_COST",
  "NONE"
]

#################   TRAINING CONFIG   ###################

